name: build-x86-64-Release

on:
  workflow_dispatch:
    inputs:
      profile:
        description: '手动输入的多个 profile，并按逗号分隔'
        required: true
        default: 'generic'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x build.sh

      - name: Setup Docker and Build
        run: |
          profiles="${{ github.event.inputs.profile }}"
          
          IFS=',' read -r -a profile_array <<< "$profiles"
          
          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"
            
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
              -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
              -v "${{ github.workspace }}/x86-64/build.sh:/home/build/immortalwrt/build.sh" \
              -e PROFILE=$profile \
              immortalwrt/imagebuilder:x86-64-openwrt-23.05.4 /bin/bash /home/build/immortalwrt/build.sh
          done

      - name: Locate squashfs firmware files
        id: locate_files
        run: |
          # 查找符合条件的固件文件
          firmware_files=$(find "${{ github.workspace }}/bin" -type f -name '*squashfs-combined*.img.gz')
          # 格式化路径，以避免多余的换行或空格
          firmware_files=$(echo "$firmware_files" | tr '\n' ' ')
          echo "Squashfs firmware files located: $firmware_files"
          echo "firmware_paths=$firmware_files" >> $GITHUB_ENV

      - name: Upload firmware to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ env.firmware_paths }}
          compression-level: 0

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # 你可以使用动态版本号或者手动指定版本
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      - name: Upload firmware to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用正确的上传 URL
          asset_path: ${{ env.firmware_paths }}  # 传递固件文件路径
          asset_name: ${{ env.firmware_name }}  # 使用提取的文件名
          asset_content_type: application/gzip  # 固件类型
        env:
          # 提取文件名
          firmware_name=$(basename "${{ env.firmware_paths }}")
          echo "firmware_name=$firmware_name" >> $GITHUB_ENV
