name: ImmortalWrt Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x build.sh

      - name: Setup Docker and Build
        run: |
          docker run --rm -i \
          --user root \
          -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
          -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
          -v "${{ github.workspace }}/build.sh:/home/build/immortalwrt/build.sh" \
          immortalwrt/imagebuilder:x86-64-openwrt-23.05.4 /bin/sh /home/build/immortalwrt/build.sh

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            ./build_dir/target-x86_64_musl/linux-x86_64/tmp/*.img.gz
