name: rockship-armv8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x build.sh

      - name: Setup Docker and Build
        run: |
          docker run --rm -i \
          --user root \
          -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
          -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
          -v "${{ github.workspace }}/Makefile_rockchip:/home/build/immortalwrt/target/linux/rockchip/Makefile" \
          -v "${{ github.workspace }}/build_rockchip.sh:/home/build/immortalwrt/build.sh" \
          immortalwrt/imagebuilder:rockchip-armv8-openwrt-24.10 /bin/sh /home/build/immortalwrt/build.sh

      - name: Locate firmware file
        id: locate_file
        run: |
          firmware_files=$(ls "${{ github.workspace }}/bin")
          echo "Firmware files located:"
          echo "$firmware_files"
          echo "firmware_paths=$(ls "${{ github.workspace }}/bin")" >> $GITHUB_ENV
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ env.firmware_path }}
          compression-level: 0
