name: rockship-armv8-squashfs-23.05.4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x build.sh

      - name: Setup Docker and Build
        run: |
          docker run --rm -i \
          --user root \
          -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
          -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
          -v "${{ github.workspace }}/build_rockchip.sh:/home/build/immortalwrt/build.sh" \
          immortalwrt/imagebuilder:rockchip-armv8-openwrt-23.05.4 /bin/bash /home/build/immortalwrt/build.sh

      - name: Locate squashfs firmware files
        id: locate_files
        run: |
          firmware_files=$(find "${{ github.workspace }}/bin" -type f -name '*squashfs*.img.gz')
          echo "Squashfs firmware files located:"
          echo "$firmware_files"
          echo "firmware_paths=$firmware_files" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ env.firmware_paths }}
          compression-level: 0
